services:
  database:
    image: postgres:14.2
    ports:
      - 54043:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=foliage
    volumes:
      - persistent_db:/var/lib/postgresql/data

volumes:
  persistent_db:
